apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-ingress
  namespace: default
spec:
  ingressClassName: ngrok
  rules:
    - host: gradually-busy-starfish.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: call-gpt-server-service
                port:
                  number: 8080
